---@meta client
--
-- AUTO-GENERATED by `akkar gen --lang luals` from the route schemas. DO NOT EDIT.
-- Regenerate after any schema change:  akkar gen <app.lua> --lang luals -o <this file>
-- Annotations only: this file has no runtime and the Lua VM never loads it.
-- It types the module `client` (the client `akkar gen --lang teal` emits,
-- compiled with `tl gen`) for the language server, so a plain-Lua caller
-- gets checked in the editor and ships nothing new.
--
-- What LuaLS catches against these classes: a wrong type, a MISSING required
-- field (`missing-fields`), a field read that the shape does not declare
-- (`undefined-field`). What it does NOT catch: an EXTRA field in a table
-- literal (LuaLS has no excess-property check), and a comparison against a
-- string literal outside a declared enum. Value constraints (min/max/length/
-- pattern) are listed per route and enforced only by the server's 422.
--
-- The error half is ONE class per route, the merge of every error body the
-- document declares: `error` is the union of the declared literals, and
-- `fields` is present on the 422 and nil otherwise.

---@class client.TransportRequest
---@field method string
---@field path string base_url, path with params filled, and the query string
---@field body any a table to send as JSON, or nil
---@field headers table<string, string>

---Returns the HTTP status and the JSON-decoded body.
---@alias client.Transport fun(request: client.TransportRequest): integer, any

---@class client.Options
---@field transport client.Transport
---@field base_url? string
---@field headers? table<string, string>

-- ---- POST /transfers  (post_transfers)
---@class client.PostTransfersBody
---@field amount integer
---@field memo? string
---@field to string

---@class client.PostTransfersResponse
---@field id string
---@field status string

---@class client.PostTransfersErrorBody
---@field error "validation failed"|"internal server error"
---@field fields? table<string, string>

---@class client.PostTransfersError
---@field status integer
---@field body client.PostTransfersErrorBody

---@class client.PostTransfersArgs
---@field body client.PostTransfersBody

-- ---- GET /users  (get_users)
---@class client.GetUsersQuery
---@field limit? integer
---@field q? string

---@class client.GetUsersResponse.UsersItem
---@field id string
---@field name string

---@class client.GetUsersResponse
---@field users client.GetUsersResponse.UsersItem[]

---@class client.GetUsersErrorBody
---@field error "validation failed"|"internal server error"
---@field fields? table<string, string>

---@class client.GetUsersError
---@field status integer
---@field body client.GetUsersErrorBody

---@class client.GetUsersArgs
---@field query? client.GetUsersQuery

-- ---- GET /users/{id}  (get_users_id)
---@class client.GetUsersIdParams
---@field id string

---@class client.GetUsersIdResponse
---@field email string
---@field id string
---@field name string

---@class client.GetUsersIdErrorBody
---@field error "validation failed"|"internal server error"
---@field fields? table<string, string>

---@class client.GetUsersIdError
---@field status integer
---@field body client.GetUsersIdErrorBody

---@class client.GetUsersIdArgs
---@field params client.GetUsersIdParams

---@class client.Client
---@field options client.Options
local Client = {}

---POST /transfers
---Enforced by the server, NOT by these types: #body.memo <= 140, #body.to >= 1, body.amount >= 1
---@param args client.PostTransfersArgs
---@return client.PostTransfersResponse? result nil exactly when `err` is set
---@return client.PostTransfersError? err the status and the typed error body
function Client:post_transfers(args) end

---GET /users
---Enforced by the server, NOT by these types: query.limit <= 100, query.limit >= 1
---@param args? client.GetUsersArgs
---@return client.GetUsersResponse? result nil exactly when `err` is set
---@return client.GetUsersError? err the status and the typed error body
function Client:get_users(args) end

---GET /users/{id}
---Enforced by the server, NOT by these types: #params.id <= 64, #params.id >= 1
---@param args client.GetUsersIdArgs
---@return client.GetUsersIdResponse? result nil exactly when `err` is set
---@return client.GetUsersIdError? err the status and the typed error body
function Client:get_users_id(args) end

---@class client
local client = {}

---@param options client.Options
---@return client.Client
function client.new(options) end

return client
