// AUTO-GENERATED by `akkar gen` from the route schemas. DO NOT EDIT.
// Regenerate after any schema change:  akkar gen <app.lua> -o <this file>
// The green light of `tsc` means this client matches the LAST GENERATED
// contract, not necessarily the running server -- keep it honest with a CI
// step that regenerates and fails on a diff (`akkar gen --check`).

export interface AkkarClientOptions {
  baseUrl?: string;
  fetch?: typeof fetch;
  headers?: Record<string, string>;
}

export class AkkarError<TBody = unknown> extends Error {
  constructor(public readonly status: number, public readonly body: TBody, operation: string) {
    super(operation + " failed: HTTP " + status);
    this.name = "AkkarError";
  }
}

// ---- POST /transfers  (post_transfers)
// Enforced by the server, NOT by these types: #body.memo <= 140, #body.to >= 1, body.amount >= 1
export interface PostTransfersBody {
  amount: number;
  memo?: string;
  to: string;
}
export interface PostTransfersResponse {
  id: string;
  status: string;
}
export type PostTransfersError = {
  error: "validation failed";
  fields: Record<string, string>;
} | {
  error: "internal server error";
};
export async function postTransfers(
  args: { body: PostTransfersBody; }, opts: AkkarClientOptions = {},
): Promise<PostTransfersResponse> {
  const base = opts.baseUrl ?? "";
  let path = "/transfers";
  const doFetch = opts.fetch ?? fetch;
  const res = await doFetch(base + path, {
    method: "POST",
    headers: {
      "content-type": "application/json",
      ...(opts.headers ?? {}),
    },
    body: JSON.stringify(args.body),
  });
  if (!res.ok) {
    throw new AkkarError<PostTransfersError>(res.status, (await res.json().catch(() => undefined)) as PostTransfersError, "post_transfers");
  }
  return (await res.json()) as PostTransfersResponse;
}

// ---- GET /users  (get_users)
// Enforced by the server, NOT by these types: query.limit <= 100, query.limit >= 1
export interface GetUsersQuery {
  limit?: number;
  q?: string;
}
export interface GetUsersResponse {
  users: {
    id: string;
    name: string;
  }[];
}
export type GetUsersError = {
  error: "validation failed";
  fields: Record<string, string>;
} | {
  error: "internal server error";
};
export async function getUsers(
  args: { query?: GetUsersQuery; }, opts: AkkarClientOptions = {},
): Promise<GetUsersResponse> {
  const base = opts.baseUrl ?? "";
  let path = "/users";
  if (args.query) {
    const q = new URLSearchParams();
    for (const [k, v] of Object.entries(args.query)) {
      if (v !== undefined && v !== null) q.set(k, String(v));
    }
    const qs = q.toString();
    if (qs) path += "?" + qs;
  }
  const doFetch = opts.fetch ?? fetch;
  const res = await doFetch(base + path, {
    method: "GET",
    headers: {
      ...(opts.headers ?? {}),
    },
  });
  if (!res.ok) {
    throw new AkkarError<GetUsersError>(res.status, (await res.json().catch(() => undefined)) as GetUsersError, "get_users");
  }
  return (await res.json()) as GetUsersResponse;
}

// ---- GET /users/{id}  (get_users_id)
// Enforced by the server, NOT by these types: #params.id <= 64, #params.id >= 1
export interface GetUsersIdParams {
  id: string;
}
export interface GetUsersIdResponse {
  email: string;
  id: string;
  name: string;
}
export type GetUsersIdError = {
  error: "validation failed";
  fields: Record<string, string>;
} | {
  error: "internal server error";
};
export async function getUsersId(
  args: { params: GetUsersIdParams; }, opts: AkkarClientOptions = {},
): Promise<GetUsersIdResponse> {
  const base = opts.baseUrl ?? "";
  let path = "/users/{id}";
  path = path.replace("{id}", encodeURIComponent(String(args.params.id)));
  const doFetch = opts.fetch ?? fetch;
  const res = await doFetch(base + path, {
    method: "GET",
    headers: {
      ...(opts.headers ?? {}),
    },
  });
  if (!res.ok) {
    throw new AkkarError<GetUsersIdError>(res.status, (await res.json().catch(() => undefined)) as GetUsersIdError, "get_users_id");
  }
  return (await res.json()) as GetUsersIdResponse;
}
